const $ = id => document.getElementById(id);
export function renderAgents(agents) { $('agentGrid').innerHTML = agents.map(({ agent, icon, status, action }) => `<article class="card agent"><div class="agent-top"><span class="agent-icon">${icon}</span><span class="status ${status.toLowerCase()}">${status}</span></div><div class="agent-name">${agent}</div><div class="agent-action">${action}</div></article>`).join(''); }
export function renderOrganizations(agents) { $('organizationGrid').innerHTML = agents.map(({ organization, description, metric, metricLabel }, index) => `<article class="card org"><div class="org-title"><i style="background:${['var(--cyan)','var(--green)','var(--amber)','var(--violet)','var(--blue)','var(--red)'][index]}"></i>${organization}</div><p>${description}</p><div class="metric">${metric} <small>${metricLabel}</small></div></article>`).join(''); }
export function addTimelineEvent({ time, title, detail, number }) { const event = document.createElement('div'); event.className = 'event'; event.innerHTML = `<div class="dot">${String(number).padStart(2, '0')}</div><b>${title}</b><p>${detail}<br>${time} IST</p>`; $('timelineList').append(event); }
export function setMission(mission) { $('selectedLocation').textContent = mission.location; $('missionTitle').textContent = mission.title; $('missionDescription').textContent = mission.description; $('riskLevel').textContent = mission.riskLevel; $('riskBadge').textContent = `RISK LEVEL: ${mission.riskLevel}`; $('agencyCount').textContent = mission.agencies; $('agentsOnline').textContent = `0/${mission.agencies}`; $('mapTitle').textContent = `${mission.location} operations area`; }
export function setProgress(completed, total) { $('tasksComplete').textContent = completed; $('agentsOnline').textContent = `${completed}/${total}`; }
export function setMissionState(message) { $('missionState').textContent = message; }
export function showSummary(summary) { $('summaryCard').hidden = false; $('summaryTitle').textContent = summary.title; $('summaryList').innerHTML = summary.items.map(item => `<li>${item}</li>`).join(''); $('report').disabled = false; }
export function toast(message) { const target = $('toast'); target.textContent = message; target.classList.add('show'); setTimeout(() => target.classList.remove('show'), 3000); }
export function setStartButton(running) { $('startMission').disabled = running; $('startMission').textContent = running ? 'Mission in progress…' : 'Start flood mission'; }
export { $ };
